package entity;

/**
 * The SubgoalQuestion entity represents a single question–answer entry
 * in the Q/A conversation for a specific subgoal.
 * Each entry stores the user's question and the system's response.
 *
 * <p>This entity is immutable. A Q/A history is built by appending new
 * SubgoalQuestion objects rather than modifying existing ones.</p>
 */
public class SubgoalQuestionAnswer {

    private final int id;
    private final int subgoalId;

    private final String questionMessage;
    private final String responseMessage;

    /**
     * Constructs a new SubgoalQuestion entity.
     *
     * @param id the unique identifier of this question–answer pair
     * @param subgoalId the ID of the subgoal this Q/A entry belongs to
     * @param questionMessage the message asked by the user
     * @param responseMessage the response generated by the system or AI
     *
     * @throws IllegalArgumentException if {@code questionMessage} is empty
     */
    public SubgoalQuestionAnswer(int id,
                           int subgoalId,
                           String questionMessage,
                           String responseMessage) {

        if (questionMessage == null || questionMessage.isEmpty()) {
            throw new IllegalArgumentException("Question message cannot be empty.");
        }

        this.id = id;
        this.subgoalId = subgoalId;
        this.questionMessage = questionMessage;
        this.responseMessage = responseMessage;
    }

    /** @return the unique ID of this question–answer entry */
    public int getId() { return id; }

    /** @return the ID of the subgoal this entry belongs to */
    public int getSubgoalId() { return subgoalId; }

    /** @return the user's question text */
    public String getQuestionMessage() { return questionMessage; }

    /** @return the system's answer text (may be null) */
    public String getResponseMessage() { return responseMessage; }
}
