package interface_adapter.plan.generate_plan;

import org.json.JSONObject;

/**
 * GeneratePlanState stores the state of the plan generation process,
 * including the user message, response message, response object, and success flag.
 */
public class GeneratePlanState {
    private String userMessage = "";
    private String responseMessage = "";
    private JSONObject responseObject = new JSONObject();
    private boolean success = false;

    /**
     * Returns the response message generated by the plan generation use case.
     * @return the response message
     */
    public String getResponseMessage() {
        return responseMessage;
    }

    /**
     * Sets the response message generated by the plan generation use case.
     * @param responseMessage the response message to store
     */
    public void setResponseMessage(String responseMessage) {
        this.responseMessage = responseMessage;
    }

    /**
     * Returns whether the plan generation process succeeded.
     * @return true if successful, false otherwise
     */
    public boolean isSuccess() {
        return success;
    }

    /**
     * Sets whether the plan generation process succeeded.
     * @param success true if successful, false otherwise
     */
    public void setSuccess(boolean success) {
        this.success = success;
    }

    /**
     * Returns the user-provided message that triggered plan generation.
     * @return the user's message
     */
    public String getUserMessage() {
        return userMessage;
    }

    /**
     * Sets the user-provided message used to generate the plan.
     * @param userMessage the user's message
     */
    public void setUserMessage(String userMessage) {
        this.userMessage = userMessage;
    }

    /**
     * Returns the JSON object representing the generated plan.
     * @return the response JSON object
     */
    public JSONObject getResponseObject() {
        return responseObject;
    }

    /**
     * Sets the JSON object containing the generated plan details.
     * @param responseObject the response JSON object
     */
    public void setResponseObject(JSONObject responseObject) {
        this.responseObject = responseObject;
    }
}
